### ISSUE TITLE
incompatibility with reactbundle 0.3.1 release

### ISSUE THREAD

**Issue by swizzly** [Thomas-Gelf/icingaweb2-module-bem#3]
Hi
It seems, that the 0.3.1 release of reactbundle has some problems with the icingaweb2 bem module (294fa21). After installation and setup, trying to run the bem module manually results in the following error messages:

```
# /usr/bin/icingacli bem daemon run --cell integration --verbose
Resetting BEM main runner for integration
PHP Fatal error:  Uncaught Error: Call to undefined method React\EventLoop\Timer\Timer::cancel() in /usr/share/icingaweb2/modules/bem/library/Bem/ImpactPoster.php:90
Stack trace:
#0 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): Icinga\Module\Bem\ImpactPoster->Icinga\Module\Bem\{closure}(0, NULL)
#1 /usr/share/icingaweb2/modules/reactbundle/vendor/react/child-process/src/Process.php(121): Evenement\EventEmitter->emit('exit', Array)
#2 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): React\ChildProcess\Process->React\ChildProcess\{closure}()
#3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/stream/src/ReadableResourceStream.php(112): Evenement\EventEmitter->emit('close')
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/react/stream/src/ReadableResourceStream.php(150): React\Stream\ReadableResourceStream->close()
#5 [internal function]: React\Stream\ReadableResourceStream->handleData(Resource id  in /usr/share/icingaweb2/modules/bem/library/Bem/ImpactPoster.php on line 90

Fatal error: Uncaught Error: Call to undefined method React\EventLoop\Timer\Timer::cancel() in /usr/share/icingaweb2/modules/bem/library/Bem/ImpactPoster.php:90
Stack trace:
#0 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): Icinga\Module\Bem\ImpactPoster->Icinga\Module\Bem\{closure}(0, NULL)
#1 /usr/share/icingaweb2/modules/reactbundle/vendor/react/child-process/src/Process.php(121): Evenement\EventEmitter->emit('exit', Array)
#2 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): React\ChildProcess\Process->React\ChildProcess\{closure}()
#3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/stream/src/ReadableResourceStream.php(112): Evenement\EventEmitter->emit('close')
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/react/stream/src/ReadableResourceStream.php(150): React\Stream\ReadableResourceStream->close()
#5 [internal function]: React\Stream\ReadableResourceStream->handleData(Resource id  in /usr/share/icingaweb2/modules/bem/library/Bem/ImpactPoster.php on line 90
```

After going back to reactbundle release 0.2.0 it just works fine, no errors.

**Comment by Thomas-Gelf** [comment]
Thanks for pointing this out! I pushed a fix, could you please give it a try?

**Comment by swizzly** [comment]
It works, thanks!

**Comment by swizzly** [comment]
It used to work, but after an hour or so it stopped and I can't restart it:

```
# /usr/bin/icingacli bem daemon run --cell integration --verbose
Resetting BEM main runner for integration
PHP Fatal error:  Uncaught Error: Call to undefined method React\EventLoop\StreamSelectLoop::cancel() in /usr/share/icingaweb2/modules/bem/library/Bem/ImpactPoster.php:90
Stack trace:
#0 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): Icinga\Module\Bem\ImpactPoster->Icinga\Module\Bem\{closure}(0, NULL)
#1 /usr/share/icingaweb2/modules/reactbundle/vendor/react/child-process/src/Process.php(130): Evenement\EventEmitter->emit('exit', Array)
#2 [internal function]: React\ChildProcess\Process->React\ChildProcess\{closure}(Object(React\EventLoop\Timer\Timer))
#3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Timer/Timers.php(89): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#5 /usr/share/icingaweb2/modules/bem/library/Bem/MainRunner.php(136): React\EventLoop\StreamSelectLoop->run()
#6 /usr/s in /usr/share/icingaweb2/modules/bem/library/Bem/ImpactPoster.php on line 90

Fatal error: Uncaught Error: Call to undefined method React\EventLoop\StreamSelectLoop::cancel() in /usr/share/icingaweb2/modules/bem/library/Bem/ImpactPoster.php:90
Stack trace:
#0 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): Icinga\Module\Bem\ImpactPoster->Icinga\Module\Bem\{closure}(0, NULL)
#1 /usr/share/icingaweb2/modules/reactbundle/vendor/react/child-process/src/Process.php(130): Evenement\EventEmitter->emit('exit', Array)
#2 [internal function]: React\ChildProcess\Process->React\ChildProcess\{closure}(Object(React\EventLoop\Timer\Timer))
#3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Timer/Timers.php(89): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#5 /usr/share/icingaweb2/modules/bem/library/Bem/MainRunner.php(136): React\EventLoop\StreamSelectLoop->run()
#6 /usr/s in /usr/share/icingaweb2/modules/bem/library/Bem/ImpactPoster.php on line 90
```

**Comment by Thomas-Gelf** [comment]
Did you move back to the latest `reactbundle` before restarting?

**Comment by swizzly** [comment]
yes, I have the current reactbundle release 0.3.1.

**Comment by swizzly** [comment]
```
# cat reactbundle/module.info 
Name: React Bundle
Version: v0.3.1
Description: ReactPHP-based 3rd party libraries
 This repository is an attempt to ship 3rd party libraries that might be useful
 for asynchronous PHP-based Icinga Web 2 modules. Please download the latest
 release and install it like any other module.
```

**Comment by Thomas-Gelf** [comment]
And you restarted the daemon after changing the bundle?

**Comment by Thomas-Gelf** [comment]
Sorry, found the error - just a second please

**Comment by Thomas-Gelf** [comment]
There you go!

**Comment by Thomas-Gelf** [comment]
Hint: 1aa00cf

**Comment by swizzly** [comment]
Many thanks, it seems to work right!
